### ISSUE TITLE
Auto install appears to be breaking faraday clients?

### ISSUE THREAD

**Issue by BRMatt** [honeycombio/faraday-honeycomb#6]
I seem to be getting this error whenever part of an application using this gem attempts to use Faraday:

```
Faraday::RackBuilder::StackLocked:
       can't modify middleware stack after making a request
     # ./vendor/ruby/2.5.0/gems/faraday-0.15.4/lib/faraday/rack_builder.rb:204:in `raise_if_locked'
     # ./vendor/ruby/2.5.0/gems/faraday-0.15.4/lib/faraday/rack_builder.rb:86:in `use'
     # ./vendor/ruby/2.5.0/gems/faraday-0.15.4/lib/faraday/rack_builder.rb:228:in `use_symbol'
     # ./vendor/ruby/2.5.0/gems/faraday-0.15.4/lib/faraday/rack_builder.rb:84:in `use'
     # ./vendor/ruby/2.5.0/gems/faraday-honeycomb-0.3.1/lib/faraday-honeycomb/auto_install.rb:32:in `block (3 levels) in auto_install!'
     # ./vendor/ruby/2.5.0/gems/faraday-0.15.4/lib/faraday/connection.rb:89:in `initialize'
     # ./vendor/ruby/2.5.0/gems/faraday-honeycomb-0.3.1/lib/faraday-honeycomb/auto_install.rb:37:in `new'
     # ./vendor/ruby/2.5.0/gems/faraday-honeycomb-0.3.1/lib/faraday-honeycomb/auto_install.rb:37:in `block (2 levels) in auto_install!'
     # ./vendor/ruby/2.5.0/gems/faraday-0.15.4/lib/faraday.rb:70:in `new'
     # ./vendor/ruby/2.5.0/gems/octokit-4.14.0/lib/octokit/connection.rb:187:in `sawyer_options'
     # ./vendor/ruby/2.5.0/gems/octokit-4.14.0/lib/octokit/connection.rb:105:in `agent'
     # ./vendor/ruby/2.5.0/gems/octokit-4.14.0/lib/octokit/connection.rb:156:in `request'
     # ./vendor/ruby/2.5.0/gems/octokit-4.14.0/lib/octokit/connection.rb:19:in `get'
     # ./vendor/ruby/2.5.0/gems/octokit-4.14.0/lib/octokit/client/users.rb:34:in `user'
     # ./app/controllers/private_api_controller.rb:28:in `block in load_current_user!'
```

These are the gems I'm using:
```
faraday (0.15.4)
faraday-honeycomb (0.3.1)
honeycomb-beeline (0.8.0)
rack-honeycomb (0.5.0)
rails (5.1.4)
```

**Comment by BRMatt** [comment]
It seems like this might be specific to octokit. When I added some byebug breakpoints to Faraday's `Connection.new` class, the first time it hits the breakpoint you [see the default middleware octokit specifies](https://github.com/octokit/octokit.rb/blob/ee1f704dce518786e968da01d7ead7010036d73b/lib/octokit/default.rb#L26-L33):

```
(byebug) self.builder
#<Faraday::RackBuilder:0x00007ff44e8b2938 @handlers=[
  Faraday::Request::Retry,
  Octokit::Middleware::FollowRedirects,
  Octokit::Response::RaiseError,
  Octokit::Response::FeedParser,
  Faraday::Adapter::NetHttp
]>
```

The next time the code hits the breakpoint you see this:

```
#<Faraday::RackBuilder:0x00007ff44e8b2938 @handlers=[
  Faraday::Request::Retry,
  Octokit::Middleware::FollowRedirects,
  Octokit::Response::RaiseError,
  Octokit::Response::FeedParser,
  Faraday::Adapter::NetHttp,
  Faraday::Honeycomb::Middleware,
  Faraday::Request::UrlEncoded,
  Faraday::Adapter::NetHttp
],
@app=#<Faraday::Request::Retry:0x00007ff44f7508c8
  @app=#<Octokit::Middleware::FollowRedirects:0x00007ff44f750cb0
    @app=#<Octokit::Response::RaiseError:0x00007ff44f750e40
      @app=#<Octokit::Response::FeedParser:0x00007ff44f750f80
        @app=#<Faraday::Adapter::NetHttp:0x00007ff44f7510c0 @cert_store=#<OpenSSL::X509::Store:0x00007ff44f746f30 @verify_callback=nil, @error=nil, @error_string=nil, @chain=nil, @time=nil>,
          @app=#<Faraday::Honeycomb::Middleware:0x00007ff44f7517c8 @logger=#<Logger:0x00007ff44e505678 @level=2, @progname=nil, @default_formatter=#<Logger::Formatter:0x00007ff44e505628 @datetime_format=nil>, @formatter=nil, @logdev=#<Logger::LogDevice:0x00007ff44e5055d8 @shift_period_suffix=nil, @shift_size=nil, @shift_age=nil, @filename=nil, @dev=#<IO:<STDERR>>, @mon_owner=nil, @mon_count=0, @mon_mutex=#<Thread::Mutex:0x00007ff44e505560>>>, @builder=#<Libhoney::Builder:0x00007ff44f751390 @libhoney=#<Libhoney::Client:0x00007ff44e505498 @builder=#<Libhoney::Builder:0x00007ff44e4ffd90 @libhoney=#<Libhoney::Client:0x00007ff44e505498 ...>, @fields={REDACTED}, @dyn_fields={}, @writekey="REDACTED", @dataset="development.deployments", @sample_rate=1, @api_host="https://api.honeycomb.io/">, @transmission=#<Libhoney::TransmissionClient:0x00007ff44e1cd668 @responses=#<Thread::SizedQueue:0x00007ff44e4ffca0>, @block_on_send=false, @block_on_responses=false, @max_batch_size=50, @send_frequency=100, @max_concurrent_batches=10, @pending_work_capacity=1000, @send_timeout=10, @user_agent="libhoney-rb/1.12.1 honeycomb-beeline/0.8.0", @send_queue=#<Thread::SizedQueue:0x00007ff44e1cc718>, @threads=[#<Thread:0x00007ff44e1ca800@/Users/mattbutton/Dev/curator/vendor/ruby/2.5.0/gems/libhoney-1.12.1/lib/libhoney/transmission.rb:135 sleep_forever>, #<Thread:0x00007ff44e1c9518@/Users/mattbutton/Dev/curator/vendor/ruby/2.5.0/gems/libhoney-1.12.1/lib/libhoney/transmission.rb:135 sleep_forever>, #<Thread:0x00007ff452ab8f30@/Users/mattbutton/Dev/curator/vendor/ruby/2.5.0/gems/libhoney-1.12.1/lib/libhoney/transmission.rb:135 sleep_forever>, #<Thread:0x00007ff452ab8df0@/Users/mattbutton/Dev/curator/vendor/ruby/2.5.0/gems/libhoney-1.12.1/lib/libhoney/transmission.rb:135 sleep_forever>, #<Thread:0x00007ff452ab8cd8@/Users/matt
button/Dev/curator/vendor/ruby/2.5.0/gems/libhoney-1.12.1/lib/libhoney/transmission.rb:135 sleep_forever>, #<Thread:0x00007ff452ab8be8@/Users/mattbutton/Dev/curator/vendor/ruby/2.5.0/gems/libhoney-1.12.1/lib/libhoney/transmission.rb:135 sleep_forever>, #<Thread:0x00007ff452ab8a
f8@/Users/mattbutton/Dev/curator/vendor/ruby/2.5.0/gems/libhoney-1.12.1/lib/libhoney/transmission.rb:135 sleep_forever>, #<Thread:0x00007ff452ab89e0@/Users/mattbutton/Dev/curator/vendor/ruby/2.5.0/gems/libhoney-1.12.1/lib/libhoney/transmission.rb:135 sleep_forever>, #<Thread:0x00007ff452ab8850@/Users/mattbutton/Dev/curator/vendor/ruby/2.5.0/gems/libhoney-1.12.1/lib/libhoney/transmission.rb:135 sleep_forever>, #<Thread:0x00007ff452ab86c0@/Users/mattbutton/Dev/curator/vendor/ruby/2.5.0/gems/libhoney-1.12.1/lib/libhoney/transmission.rb:135 sleep_forever
>], @lock=#<Thread::Mutex:0x00007ff44e1caa58>>, @user_agent_addition="honeycomb-beeline/0.8.0", @block_on_send=false, @block_on_responses=false, @max_batch_size=50, @send_frequency=100, @max_concurrent_batches=10, @pending_work_capacity=1000, @responses=#<Thread::SizedQueue:0x00007ff44e4ffca0>, @lock=#<Thread::Mutex:0x00007ff44e4ffc50>>, @fields={"meta.beeline_version"=>"0.8.0", "meta.local_hostname"=>"Matts-MacBook-Pro-3.local", "service_name"=>"curator", "type"=>"http_client", "meta.package"=>"faraday", "meta.package_version"=>"0.15.4"}, @dyn_field
s={}, @writekey="c9c74b7fd50b30df3bc16fc71a0ffde3", @dataset="development.deployments", @sample_rate=1, @api_host="https://api.honeycomb.io/">,
            @app=#<Faraday::Request::UrlEncoded:0x00007ff44f7517f0
              @app=#<Faraday::Adapter::NetHttp:0x00007ff44f7710c8 @cert_store=#<OpenSSL::X509
::Store:0x00007ff452a22490 @verify_callback=nil, @error=nil, @error_string=nil, @chain=nil, @time=nil>,
                @app=#<Proc:0x00007ff44f771370@/Users/mattbutton/Dev/curator/vendor/ruby/2.5.0/gems/faraday-0.15.4/lib/faraday/rack_builder.rb:157 (lambda)>, @connection_options={}, @config_
block=nil>>>, @connection_options={}, @config_block=nil>>>, @options={}, @convert_to_get=#<Set: {303}>>, @options=#<Faraday::Request::Retry::Options max=2, interval=0.0, max_interval=1.7976931348623157e+308, interval_randomness=0.0, backoff_factor=1.0, exceptions=[Octokit::ServerError], methods=[:delete, :get, :head, :options, :put], retry_if=#<Proc:0x00007ff44f14f5f0@/Users/mattbutton/Dev/curator/vendor/ruby/2.5.
0/gems/faraday-0.15.4/lib/faraday/request/retry.rb:30 (lambda)>, retry_block=#<Proc:0x00007ff4533372b0@/Users/mattbutton/Dev/curator/vendor/ruby/2.5.0/gems/faraday-0.15.4/lib/faraday/request/retry.rb:73>, retry_statuses=[]>, @errmatch=#<Module:0x00007ff44f750710>>>
```

It seems like `faraday-honeycomb` assumes that every Faraday connection will be given a fresh middleware stack, but it seems this is only the case when Faraday [was not given a builder by its caller](https://github.com/lostisland/faraday/blob/a217471dc69cfd56604ae79f40de71086f7f5561/lib/faraday/connection.rb#L77-L80). It appears that Faraday [locks the middleware when it makes the request](https://github.com/lostisland/faraday/blob/a217471dc69cfd56604ae79f40de71086f7f5561/lib/faraday/rack_builder.rb#L145-L154), so when `faraday-honeycomb` receives that second middleware stack it's trying to modify a locked set of middleware.

Maybe this library should only add its middleware [if the builder is not locked](https://github.com/lostisland/faraday/blob/a217471dc69cfd56604ae79f40de71086f7f5561/lib/faraday/rack_builder.rb#L88-L90)?

It's also worth noting that in the second set of middleware, the honeycomb middleware appears to be invoked _after_ the `Net::Http` adapter, so it seems like [the timings that the honeycomb middleware measures](https://github.com/honeycombio/faraday-honeycomb/blob/master/lib/faraday/honeycomb/middleware.rb#L40) would be irrelevant as the request would already have been made by that point...?

Maybe we should inspect the handlers and if the last one is an adapter, insert before it?

**Comment by martin308** [comment]
@BRMatt thanks for the detailed report 🙏 I've made a PR which should account for this, let me know if this fixes this issue for you
